# undertow
server:
  undertow:
    accesslog:
      dir: target/logs/undertow
      enabled: true
      pattern: common

# multipart
multipart:
    maxFileSize: 2Mb

# debug
debug: true

# mongo
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    mongodb:
#      uri: mongodb://root:12345678@localhost:27017/fs?authSource=admin
#      uri: mongodb://root:12345678@10.0.23.55:27017/fs?authSource=admin
      uri: mongodb://localhost:27017/fs

management:
  context-path: /manage

logging:
  level:
    org.springframework.security: DEBUG

oauth2:
  authorizationServer:
    uri: http://localhost:8080
